In [485]:
import numpy as np
import pandas as pd
import tensorflow as tf
import torch
from torch import nn
from sentence_transformers import SentenceTransformer, util
from tensorflow.keras.applications.vgg16 import VGG16

In [486]:
df = pd.read_csv(r"labels.csv")
df.head()

Unnamed: 0    image_name  \
0           0   image_1.jpg   
1           1  image_2.jpeg   
2           2   image_3.JPG   
3           3   image_4.png   
4           4   image_5.png   

                                            text_ocr  \
0  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1  The best of #10 YearChallenge! Completed in le...   
2  Sam Thorne @Strippin ( Follow Follow Saw every...   
3              10 Year Challenge - Sweet Dee Edition   
4  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   

                                      text_corrected      humour  \
0  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   hilarious   
1  The best of #10 YearChallenge! Completed in le...   not_funny   
2  Sam Thorne @Strippin ( Follow Follow Saw every...  very_funny   
3              10 Year Challenge - Sweet Dee Edition  very_funny   
4  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   hilarious   

           sarcasm       offensive      motivational overall_sentiment  
0          general   not_offensive  not_motivational     very_positive  
1          general   not_offensive      motivational     very_positive  
2    not_sarcastic   not_offensive  not_motivational          positive  
3  twisted_meaning  very_offensive      motivational          positive  
4     very_twisted  very_offensive  not_motivational           neutral

In [487]:
df = df.iloc[: , 1:]
df.head()

image_name                                           text_ocr  \
0   image_1.jpg  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1  image_2.jpeg  The best of #10 YearChallenge! Completed in le...   
2   image_3.JPG  Sam Thorne @Strippin ( Follow Follow Saw every...   
3   image_4.png              10 Year Challenge - Sweet Dee Edition   
4   image_5.png  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   

                                      text_corrected      humour  \
0  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   hilarious   
1  The best of #10 YearChallenge! Completed in le...   not_funny   
2  Sam Thorne @Strippin ( Follow Follow Saw every...  very_funny   
3              10 Year Challenge - Sweet Dee Edition  very_funny   
4  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   hilarious   

           sarcasm       offensive      motivational overall_sentiment  
0          general   not_offensive  not_motivational     very_positive  
1          general   not_offensive      motivational     very_positive  
2    not_sarcastic   not_offensive  not_motivational          positive  
3  twisted_meaning  very_offensive      motivational          positive  
4     very_twisted  very_offensive  not_motivational           neutral

In [488]:
df.shape

(6992, 8)

In [489]:
df['overall_sentiment'].mask(df['overall_sentiment'] == 'positive', 1, inplace=True)
df['overall_sentiment'].mask(df['overall_sentiment'] == 'very_positive', 1, inplace=True)
df['overall_sentiment'].mask(df['overall_sentiment'] == 'negative', 2, inplace=True)
df['overall_sentiment'].mask(df['overall_sentiment'] == 'very_negative', 2, inplace=True)
df['overall_sentiment'].mask(df['overall_sentiment'] == 'neutral', 0, inplace=True)

In [490]:
df['overall_sentiment'].value_counts()

1    4160
0    2201
2     631
Name: overall_sentiment, dtype: int64

In [491]:
Duplicate_negative_Sentiment_rows=df[df['overall_sentiment']==2]
Duplicate_negative_Sentiment_rows.shape

(631, 8)

In [492]:
for i in range(10):
    df = df.sample(frac = 1)

In [493]:
df.dropna(axis=0, how="any", thresh=None, subset=None, inplace=True)

In [494]:
df.isnull().sum()

image_name           0
text_ocr             0
text_corrected       0
humour               0
sarcasm              0
offensive            0
motivational         0
overall_sentiment    0
dtype: int64

# Text Embedding

In [495]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['text_corrected'])
def embedding_for_vocab(filepath, word_index,embedding_dim):
    vocab_size = len(word_index) + 1
    embedding_matrix_vocab = np.zeros((vocab_size,embedding_dim))

    with open(filepath, encoding="utf8") as f:
        for line in f:
            word, *vector = line.split()
            if word in word_index:
                idx = word_index[word]
                embedding_matrix_vocab[idx] = np.array(vector, dtype=np.float32)[:embedding_dim]

    return embedding_matrix_vocab
embedding_dim = 50
embedding_matrix_vocab = embedding_for_vocab("E:\glove.6B.300d.txt\glove.6B.300d.txt", tokenizer.word_index,embedding_dim)

print("Dense vector for first word is => ",embedding_matrix_vocab[1])

Dense vector for first word is =>  [ 0.04656     0.21318001 -0.0074364  -0.45853999 -0.035639    0.23643
 -0.28836     0.21521001 -0.13485999 -1.64129996 -0.26091     0.032434
  0.056621   -0.043296   -0.021672    0.22476    -0.075129   -0.067018
 -0.14247     0.038825   -0.18951     0.29977     0.39304999  0.17887001
 -0.17343    -0.21178     0.23616999 -0.063681   -0.42318001 -0.11661
  0.093754    0.17296    -0.33072999  0.49112001 -0.68994999 -0.092462
  0.24742    -0.17991     0.097908    0.083118    0.15299    -0.27276
 -0.038934    0.54452997  0.53737003  0.29104999 -0.0073514   0.04788
 -0.40759999 -0.026759  ]


In [496]:
text_model = SentenceTransformer('stsb-distilbert-base')
text_model.max_seq_length = 128

In [497]:
def Calulate_textEmbeddings(model,text):
    return model.encode(text, convert_to_tensor=True)

# Image Embedding

In [498]:
img_model = VGG16(input_shape = (224, 224, 3),include_top = False,weights = 'imagenet')

In [499]:
def Calulate_imageEmbeddings(model,imagePath):   
    image = tf.keras.preprocessing.image.load_img(imagePath,target_size=(224,224))
    input_arr = tf.keras.preprocessing.image.img_to_array(image)
    input_arr = np.array([input_arr])
    img_embeddings = model(input_arr)
    meanImgEmb1 = np.mean(img_embeddings,axis =0)
    meanImgEmb = np.mean(meanImgEmb1,axis=0)
    return meanImgEmb

# Concatenating Image and Text Embeddings

In [500]:
# text_embeddings={}
# image_embeddings={}
# cembList=[]
# start_time = time.time()
# i=1
# for index,row in  df.iterrows():
#     text_embeddings[row[0]] = get_textEmbeddings(text_model,str(row[1]))
#     image_embeddings[row[0]] = get_imageEmbeddings(img_model,r'C:\Users\MOON COMPUTER\Desktop\images'+'\\'+row[0])
#     cmb_emb = np.concatenate((text_embeddings[row[0]],image_embeddings[row[0]]),axis=0)
#     norm = np.linalg.norm(cmb_emb)
#     cmb_emb_normal = cmb_emb/norm
#     cembList.append(cmb_emb_normal)
#     print(i)
#     i+=1
# np.savetxt('combinedEmbedding1.txt',cembList)

In [501]:
cembList = np.loadtxt('combinedEmbedding1.txt')
cembList

array([[-0.00935429,  0.02323051,  0.01667355, ...,  0.00638428,
         0.        ,  0.        ],
       [-0.00949132, -0.00060132,  0.02634004, ...,  0.04302868,
         0.00118084,  0.        ],
       [ 0.01757763,  0.01517454,  0.03182393, ...,  0.02904396,
         0.        ,  0.        ],
       ...,
       [ 0.00756703,  0.04082896,  0.0248953 , ...,  0.02749274,
         0.        ,  0.        ],
       [ 0.01357932, -0.00924617,  0.02497569, ...,  0.02593378,
         0.00798608,  0.00781092],
       [ 0.00491172,  0.01239794, -0.00674349, ...,  0.0236083 ,
         0.00174118,  0.00173017]])

In [502]:
y=list(df.iloc[:,-1])
y_train=y[:int(len(cembList)*0.8)]
y_test=y[int(len(cembList)*0.8):int(len(cembList))]
print(y_test)

[1, 1, 1, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 2, 2, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 

In [503]:
X_train_embed=cembList[:int(len(cembList)*0.8)]
X_test_embed=cembList[int(len(cembList)*0.8):]

In [504]:
X_test_embed = X_test_embed.astype(np.float32)
X_train_embed = X_train_embed.astype(np.float32)

In [505]:
len(X_test_embed)

1366

In [506]:
dataweights=torch.tensor(cembList)

In [507]:
class MultiModal(nn.Module): #For images
    def __init__(self):
        super(MultiModal, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(1792, 1048),
            nn.ReLU(),
            nn.Linear(1048, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Softmax(),
            nn.Linear(512, 3),
        )
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [508]:
model=MultiModal()

In [509]:
def train_loop(X,y, model, loss_fn, optimizer,batch_size=2):
    size = len(X)
    num_batches = len(X)//batch_size
    prev_batch=0
    lastbatch,lastbatch_size=False,0
    for batch in range(num_batches):
        pred = model(X[prev_batch:prev_batch+batch_size])
        print(pred)
        loss = loss_fn(pred, y[prev_batch:prev_batch+batch_size])
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        loss, current = loss.item(), prev_batch+batch_size
        print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")
        prev_batch=prev_batch+batch_size


def test_loop(X,y, model, loss_fn,batch_size=2):
    size = len(X)
    num_batches = size//batch_size
    test_loss, correct, correct2 = 0, 0, 0
    prev_batch=0
    with torch.no_grad():
        for batch in range(num_batches):
            pred = model(X[prev_batch:prev_batch+batch_size])
            test_loss += loss_fn(pred, y[prev_batch:prev_batch+batch_size]).item()
            correct += (pred.argmax(1) == y[prev_batch:prev_batch+batch_size]).type(torch.float).sum().item()
            prev_batch=prev_batch+batch_size
    test_loss /= num_batches
    acc=correct/ size
    print(f"Test Error: \n Accuracy: {(100*acc):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [510]:
learning_rate = 1e-3
batch_size = 2
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
epochs = 1
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(torch.tensor(X_train_embed),torch.tensor(y_train), model, loss_fn, optimizer,batch_size)
    test_loop(torch.tensor(X_test_embed),torch.tensor(y_test), model, loss_fn,batch_size)

Epoch 1
-------------------------------
tensor([[-0.0093,  0.0362,  0.0307],
        [-0.0093,  0.0362,  0.0307]], grad_fn=<AddmmBackward0>)
loss: 1.081795  [    2/ 5464]
tensor([[-0.0114,  0.0383,  0.0286],
        [-0.0114,  0.0383,  0.0286]], grad_fn=<AddmmBackward0>)
loss: 1.079047  [    4/ 5464]
tensor([[-0.0134,  0.0404,  0.0265],
        [-0.0134,  0.0404,  0.0266]], grad_fn=<AddmmBackward0>)
loss: 1.076291  [    6/ 5464]
tensor([[-0.0155,  0.0426,  0.0244],
        [-0.0155,  0.0426,  0.0244]], grad_fn=<AddmmBackward0>)
loss: 1.073465  [    8/ 5464]


C:\Users\MOON COMPUTER\anaconda3\lib\site-packages\torch\nn\modules\container.py:141: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


tensor([[-0.0176,  0.0449,  0.0223],
        [-0.0176,  0.0449,  0.0223]], grad_fn=<AddmmBackward0>)
loss: 1.101819  [   10/ 5464]
tensor([[-0.0191,  0.0472,  0.0200],
        [-0.0190,  0.0470,  0.0201]], grad_fn=<AddmmBackward0>)
loss: 1.067896  [   12/ 5464]
tensor([[-0.0208,  0.0496,  0.0176],
        [-0.0207,  0.0496,  0.0177]], grad_fn=<AddmmBackward0>)
loss: 1.100112  [   14/ 5464]
tensor([[-0.0220,  0.0521,  0.0151],
        [-0.0219,  0.0520,  0.0151]], grad_fn=<AddmmBackward0>)
loss: 1.062102  [   16/ 5464]
tensor([[-0.0233,  0.0546,  0.0126],
        [-0.0234,  0.0547,  0.0124]], grad_fn=<AddmmBackward0>)
loss: 1.098023  [   18/ 5464]
tensor([[-0.0246,  0.0583,  0.0090],
        [-0.0245,  0.0577,  0.0094]], grad_fn=<AddmmBackward0>)
loss: 1.096493  [   20/ 5464]
tensor([[-0.0252,  0.0608,  0.0061],
        [-0.0251,  0.0600,  0.0067]], grad_fn=<AddmmBackward0>)
loss: 1.095728  [   22/ 5464]
tensor([[-0.0256,  0.0641,  0.0022],
        [-0.0255,  0.0638,  0.0025]], grad_fn=

tensor([[ 0.0003,  0.1577, -0.1088],
        [ 0.0003,  0.1577, -0.1088]], grad_fn=<AddmmBackward0>)
loss: 1.096566  [  138/ 5464]
tensor([[ 0.0006,  0.1586, -0.1103],
        [ 0.0006,  0.1586, -0.1103]], grad_fn=<AddmmBackward0>)
loss: 1.041435  [  140/ 5464]
tensor([[ 0.0010,  0.1594, -0.1119],
        [ 0.0010,  0.1594, -0.1119]], grad_fn=<AddmmBackward0>)
loss: 1.040797  [  142/ 5464]
tensor([[ 0.0015,  0.1602, -0.1136],
        [ 0.0015,  0.1602, -0.1136]], grad_fn=<AddmmBackward0>)
loss: 1.177032  [  144/ 5464]
tensor([[ 0.0021,  0.1608, -0.1149],
        [ 0.0021,  0.1608, -0.1149]], grad_fn=<AddmmBackward0>)
loss: 1.098086  [  146/ 5464]
tensor([[ 0.0024,  0.1613, -0.1159],
        [ 0.0024,  0.1613, -0.1159]], grad_fn=<AddmmBackward0>)
loss: 0.959720  [  148/ 5464]
tensor([[ 0.0025,  0.1622, -0.1171],
        [ 0.0025,  0.1622, -0.1171]], grad_fn=<AddmmBackward0>)
loss: 0.958883  [  150/ 5464]
tensor([[ 0.0023,  0.1632, -0.1183],
        [ 0.0023,  0.1632, -0.1183]], grad_fn=

loss: 0.901306  [  262/ 5464]
tensor([[-0.0048,  0.2207, -0.1915],
        [-0.0048,  0.2207, -0.1915]], grad_fn=<AddmmBackward0>)
loss: 1.013029  [  264/ 5464]
tensor([[-0.0050,  0.2217, -0.1928],
        [-0.0050,  0.2218, -0.1928]], grad_fn=<AddmmBackward0>)
loss: 0.899269  [  266/ 5464]
tensor([[-0.0053,  0.2230, -0.1941],
        [-0.0053,  0.2230, -0.1941]], grad_fn=<AddmmBackward0>)
loss: 1.126379  [  268/ 5464]
tensor([[-0.0052,  0.2239, -0.1955],
        [-0.0052,  0.2239, -0.1955]], grad_fn=<AddmmBackward0>)
loss: 1.011749  [  270/ 5464]
tensor([[-0.0050,  0.2247, -0.1969],
        [-0.0050,  0.2247, -0.1969]], grad_fn=<AddmmBackward0>)
loss: 1.011243  [  272/ 5464]
tensor([[-0.0047,  0.2255, -0.1984],
        [-0.0047,  0.2255, -0.1984]], grad_fn=<AddmmBackward0>)
loss: 1.010708  [  274/ 5464]
tensor([[-0.0043,  0.2263, -0.2000],
        [-0.0043,  0.2263, -0.2000]], grad_fn=<AddmmBackward0>)
loss: 1.010149  [  276/ 5464]
tensor([[-0.0038,  0.2270, -0.2016],
        [-0.0038

tensor([[ 0.0210,  0.2636, -0.2799],
        [ 0.0210,  0.2636, -0.2799]], grad_fn=<AddmmBackward0>)
loss: 0.860880  [  394/ 5464]
tensor([[ 0.0217,  0.2641, -0.2814],
        [ 0.0217,  0.2641, -0.2814]], grad_fn=<AddmmBackward0>)
loss: 0.981677  [  396/ 5464]
tensor([[ 0.0225,  0.2646, -0.2829],
        [ 0.0225,  0.2646, -0.2829]], grad_fn=<AddmmBackward0>)
loss: 0.860086  [  398/ 5464]
tensor([[ 0.0229,  0.2653, -0.2844],
        [ 0.0229,  0.2653, -0.2844]], grad_fn=<AddmmBackward0>)
loss: 1.101832  [  400/ 5464]
tensor([[ 0.0238,  0.2658, -0.2860],
        [ 0.0238,  0.2658, -0.2860]], grad_fn=<AddmmBackward0>)
loss: 1.101072  [  402/ 5464]
tensor([[ 0.0249,  0.2659, -0.2876],
        [ 0.0249,  0.2659, -0.2876]], grad_fn=<AddmmBackward0>)
loss: 1.135754  [  404/ 5464]
tensor([[ 0.0258,  0.2661, -0.2889],
        [ 0.0258,  0.2661, -0.2889]], grad_fn=<AddmmBackward0>)
loss: 0.858863  [  406/ 5464]
tensor([[ 0.0263,  0.2666, -0.2902],
        [ 0.0263,  0.2666, -0.2902]], grad_fn=

tensor([[ 0.0447,  0.3005, -0.3608],
        [ 0.0447,  0.3005, -0.3608]], grad_fn=<AddmmBackward0>)
loss: 0.828754  [  524/ 5464]
tensor([[ 0.0440,  0.3019, -0.3620],
        [ 0.0440,  0.3019, -0.3620]], grad_fn=<AddmmBackward0>)
loss: 1.085335  [  526/ 5464]
tensor([[ 0.0438,  0.3029, -0.3633],
        [ 0.0438,  0.3029, -0.3633]], grad_fn=<AddmmBackward0>)
loss: 0.956102  [  528/ 5464]
tensor([[ 0.0438,  0.3038, -0.3645],
        [ 0.0437,  0.3038, -0.3645]], grad_fn=<AddmmBackward0>)
loss: 1.085792  [  530/ 5464]
tensor([[ 0.0441,  0.3044, -0.3659],
        [ 0.0441,  0.3044, -0.3659]], grad_fn=<AddmmBackward0>)
loss: 0.825208  [  532/ 5464]
tensor([[ 0.0442,  0.3053, -0.3672],
        [ 0.0442,  0.3053, -0.3672]], grad_fn=<AddmmBackward0>)
loss: 0.954998  [  534/ 5464]
tensor([[ 0.0444,  0.3061, -0.3687],
        [ 0.0444,  0.3061, -0.3687]], grad_fn=<AddmmBackward0>)
loss: 1.085448  [  536/ 5464]
tensor([[ 0.0449,  0.3065, -0.3701],
        [ 0.0449,  0.3065, -0.3701]], grad_fn=

tensor([[ 0.0457,  0.3444, -0.4271],
        [ 0.0457,  0.3444, -0.4271]], grad_fn=<AddmmBackward0>)
loss: 0.939678  [  658/ 5464]
tensor([[ 0.0461,  0.3446, -0.4278],
        [ 0.0461,  0.3446, -0.4278]], grad_fn=<AddmmBackward0>)
loss: 1.088662  [  660/ 5464]
tensor([[ 0.0469,  0.3445, -0.4287],
        [ 0.0469,  0.3445, -0.4287]], grad_fn=<AddmmBackward0>)
loss: 0.790349  [  662/ 5464]
tensor([[ 0.0474,  0.3447, -0.4296],
        [ 0.0474,  0.3447, -0.4296]], grad_fn=<AddmmBackward0>)
loss: 1.326007  [  664/ 5464]
tensor([[ 0.0480,  0.3446, -0.4303],
        [ 0.0480,  0.3446, -0.4303]], grad_fn=<AddmmBackward0>)
loss: 0.938626  [  666/ 5464]
tensor([[ 0.0486,  0.3446, -0.4310],
        [ 0.0486,  0.3446, -0.4310]], grad_fn=<AddmmBackward0>)
loss: 0.938379  [  668/ 5464]
tensor([[ 0.0492,  0.3446, -0.4318],
        [ 0.0492,  0.3446, -0.4318]], grad_fn=<AddmmBackward0>)
loss: 1.085798  [  670/ 5464]
tensor([[ 0.0502,  0.3444, -0.4327],
        [ 0.0502,  0.3444, -0.4327]], grad_fn=

tensor([[ 0.0431,  0.3721, -0.4643],
        [ 0.0431,  0.3721, -0.4643]], grad_fn=<AddmmBackward0>)
loss: 0.766816  [  786/ 5464]
tensor([[ 0.0428,  0.3732, -0.4654],
        [ 0.0428,  0.3732, -0.4654]], grad_fn=<AddmmBackward0>)
loss: 0.765918  [  788/ 5464]
tensor([[ 0.0423,  0.3744, -0.4666],
        [ 0.0423,  0.3744, -0.4666]], grad_fn=<AddmmBackward0>)
loss: 0.930915  [  790/ 5464]
tensor([[ 0.0419,  0.3755, -0.4678],
        [ 0.0419,  0.3755, -0.4678]], grad_fn=<AddmmBackward0>)
loss: 0.930693  [  792/ 5464]
tensor([[ 0.0417,  0.3766, -0.4690],
        [ 0.0417,  0.3766, -0.4690]], grad_fn=<AddmmBackward0>)
loss: 0.930445  [  794/ 5464]
tensor([[ 0.0416,  0.3775, -0.4703],
        [ 0.0416,  0.3775, -0.4703]], grad_fn=<AddmmBackward0>)
loss: 0.762234  [  796/ 5464]
tensor([[ 0.0413,  0.3786, -0.4716],
        [ 0.0413,  0.3786, -0.4716]], grad_fn=<AddmmBackward0>)
loss: 0.929923  [  798/ 5464]
tensor([[ 0.0412,  0.3797, -0.4729],
        [ 0.0412,  0.3797, -0.4729]], grad_fn=

loss: 1.216979  [  912/ 5464]
tensor([[ 0.0686,  0.4032, -0.5439],
        [ 0.0686,  0.4032, -0.5439]], grad_fn=<AddmmBackward0>)
loss: 0.910891  [  914/ 5464]
tensor([[ 0.0684,  0.4040, -0.5449],
        [ 0.0684,  0.4040, -0.5449]], grad_fn=<AddmmBackward0>)
loss: 0.910712  [  916/ 5464]
tensor([[ 0.0684,  0.4048, -0.5460],
        [ 0.0684,  0.4048, -0.5460]], grad_fn=<AddmmBackward0>)
loss: 0.910509  [  918/ 5464]
tensor([[ 0.0684,  0.4054, -0.5471],
        [ 0.0684,  0.4054, -0.5471]], grad_fn=<AddmmBackward0>)
loss: 1.078786  [  920/ 5464]
tensor([[ 0.0689,  0.4058, -0.5482],
        [ 0.0689,  0.4058, -0.5482]], grad_fn=<AddmmBackward0>)
loss: 0.909996  [  922/ 5464]
tensor([[ 0.0694,  0.4061, -0.5494],
        [ 0.0694,  0.4061, -0.5494]], grad_fn=<AddmmBackward0>)
loss: 0.741306  [  924/ 5464]
tensor([[ 0.0696,  0.4067, -0.5506],
        [ 0.0696,  0.4067, -0.5506]], grad_fn=<AddmmBackward0>)
loss: 0.740861  [  926/ 5464]
tensor([[ 0.0696,  0.4075, -0.5518],
        [ 0.0696

loss: 0.898128  [ 1042/ 5464]
tensor([[ 0.0729,  0.4418, -0.6096],
        [ 0.0729,  0.4418, -0.6096]], grad_fn=<AddmmBackward0>)
loss: 0.713460  [ 1044/ 5464]
tensor([[ 0.0733,  0.4421, -0.6106],
        [ 0.0733,  0.4421, -0.6106]], grad_fn=<AddmmBackward0>)
loss: 0.713188  [ 1046/ 5464]
tensor([[ 0.0733,  0.4428, -0.6117],
        [ 0.0733,  0.4428, -0.6117]], grad_fn=<AddmmBackward0>)
loss: 0.712712  [ 1048/ 5464]
tensor([[ 0.0732,  0.4436, -0.6128],
        [ 0.0732,  0.4436, -0.6128]], grad_fn=<AddmmBackward0>)
loss: 1.425446  [ 1050/ 5464]
tensor([[ 0.0732,  0.4441, -0.6135],
        [ 0.0732,  0.4441, -0.6135]], grad_fn=<AddmmBackward0>)
loss: 0.711673  [ 1052/ 5464]
tensor([[ 0.0730,  0.4448, -0.6143],
        [ 0.0730,  0.4448, -0.6143]], grad_fn=<AddmmBackward0>)
loss: 0.897016  [ 1054/ 5464]
tensor([[ 0.0729,  0.4454, -0.6152],
        [ 0.0729,  0.4454, -0.6152]], grad_fn=<AddmmBackward0>)
loss: 0.896880  [ 1056/ 5464]
tensor([[ 0.0729,  0.4460, -0.6161],
        [ 0.0729

tensor([[ 0.0391,  0.4945, -0.6461],
        [ 0.0391,  0.4945, -0.6461]], grad_fn=<AddmmBackward0>)
loss: 1.240088  [ 1170/ 5464]
tensor([[ 0.0383,  0.4951, -0.6460],
        [ 0.0383,  0.4951, -0.6460]], grad_fn=<AddmmBackward0>)
loss: 0.669241  [ 1172/ 5464]
tensor([[ 0.0374,  0.4959, -0.6461],
        [ 0.0374,  0.4959, -0.6461]], grad_fn=<AddmmBackward0>)
loss: 0.668531  [ 1174/ 5464]
tensor([[ 0.0364,  0.4970, -0.6462],
        [ 0.0364,  0.4970, -0.6462]], grad_fn=<AddmmBackward0>)
loss: 0.897978  [ 1176/ 5464]
tensor([[ 0.0355,  0.4979, -0.6465],
        [ 0.0355,  0.4979, -0.6465]], grad_fn=<AddmmBackward0>)
loss: 1.129238  [ 1178/ 5464]
tensor([[ 0.0352,  0.4984, -0.6469],
        [ 0.0352,  0.4984, -0.6469]], grad_fn=<AddmmBackward0>)
loss: 0.666501  [ 1180/ 5464]
tensor([[ 0.0347,  0.4991, -0.6474],
        [ 0.0347,  0.4991, -0.6474]], grad_fn=<AddmmBackward0>)
loss: 0.665903  [ 1182/ 5464]
tensor([[ 0.0341,  0.5001, -0.6480],
        [ 0.0341,  0.5001, -0.6480]], grad_fn=

tensor([[ 0.0224,  0.5292, -0.6775],
        [ 0.0224,  0.5292, -0.6775]], grad_fn=<AddmmBackward0>)
loss: 0.896094  [ 1300/ 5464]
tensor([[ 0.0219,  0.5297, -0.6776],
        [ 0.0219,  0.5297, -0.6776]], grad_fn=<AddmmBackward0>)
loss: 0.642294  [ 1302/ 5464]
tensor([[ 0.0212,  0.5304, -0.6778],
        [ 0.0212,  0.5304, -0.6778]], grad_fn=<AddmmBackward0>)
loss: 0.896300  [ 1304/ 5464]
tensor([[ 0.0207,  0.5310, -0.6781],
        [ 0.0207,  0.5310, -0.6781]], grad_fn=<AddmmBackward0>)
loss: 1.245768  [ 1306/ 5464]
tensor([[ 0.0201,  0.5315, -0.6781],
        [ 0.0201,  0.5315, -0.6781]], grad_fn=<AddmmBackward0>)
loss: 0.896488  [ 1308/ 5464]
tensor([[ 0.0197,  0.5320, -0.6782],
        [ 0.0197,  0.5320, -0.6782]], grad_fn=<AddmmBackward0>)
loss: 0.640423  [ 1310/ 5464]
tensor([[ 0.0191,  0.5326, -0.6784],
        [ 0.0191,  0.5326, -0.6784]], grad_fn=<AddmmBackward0>)
loss: 0.896656  [ 1312/ 5464]
tensor([[ 0.0187,  0.5332, -0.6787],
        [ 0.0187,  0.5332, -0.6787]], grad_fn=

loss: 0.891078  [ 1424/ 5464]
tensor([[ 0.0318,  0.5354, -0.7003],
        [ 0.0318,  0.5354, -0.7003]], grad_fn=<AddmmBackward0>)
loss: 0.891011  [ 1426/ 5464]
tensor([[ 0.0319,  0.5357, -0.7008],
        [ 0.0319,  0.5357, -0.7008]], grad_fn=<AddmmBackward0>)
loss: 0.639047  [ 1428/ 5464]
tensor([[ 0.0318,  0.5361, -0.7015],
        [ 0.0318,  0.5361, -0.7015]], grad_fn=<AddmmBackward0>)
loss: 0.890844  [ 1430/ 5464]
tensor([[ 0.0319,  0.5365, -0.7022],
        [ 0.0319,  0.5365, -0.7022]], grad_fn=<AddmmBackward0>)
loss: 0.890743  [ 1432/ 5464]
tensor([[ 0.0320,  0.5369, -0.7029],
        [ 0.0320,  0.5369, -0.7029]], grad_fn=<AddmmBackward0>)
loss: 1.258081  [ 1434/ 5464]
tensor([[ 0.0319,  0.5372, -0.7033],
        [ 0.0319,  0.5372, -0.7033]], grad_fn=<AddmmBackward0>)
loss: 0.890573  [ 1436/ 5464]
tensor([[ 0.0320,  0.5375, -0.7038],
        [ 0.0320,  0.5375, -0.7038]], grad_fn=<AddmmBackward0>)
loss: 0.890499  [ 1438/ 5464]
tensor([[ 0.0322,  0.5377, -0.7044],
        [ 0.0322

tensor([[ 0.0427,  0.5580, -0.7510],
        [ 0.0427,  0.5580, -0.7510]], grad_fn=<AddmmBackward0>)
loss: 1.139878  [ 1552/ 5464]
tensor([[ 0.0429,  0.5585, -0.7520],
        [ 0.0429,  0.5585, -0.7520]], grad_fn=<AddmmBackward0>)
loss: 0.624244  [ 1554/ 5464]
tensor([[ 0.0429,  0.5592, -0.7530],
        [ 0.0429,  0.5592, -0.7530]], grad_fn=<AddmmBackward0>)
loss: 1.279865  [ 1556/ 5464]
tensor([[ 0.0427,  0.5598, -0.7536],
        [ 0.0427,  0.5598, -0.7536]], grad_fn=<AddmmBackward0>)
loss: 0.881894  [ 1558/ 5464]
tensor([[ 0.0426,  0.5603, -0.7543],
        [ 0.0426,  0.5603, -0.7543]], grad_fn=<AddmmBackward0>)
loss: 0.622990  [ 1560/ 5464]
tensor([[ 0.0423,  0.5610, -0.7550],
        [ 0.0423,  0.5610, -0.7550]], grad_fn=<AddmmBackward0>)
loss: 0.622468  [ 1562/ 5464]
tensor([[ 0.0419,  0.5619, -0.7558],
        [ 0.0419,  0.5619, -0.7558]], grad_fn=<AddmmBackward0>)
loss: 0.621797  [ 1564/ 5464]
tensor([[ 0.0413,  0.5629, -0.7567],
        [ 0.0413,  0.5629, -0.7567]], grad_fn=

loss: 0.602242  [ 1676/ 5464]
tensor([[ 0.0275,  0.5881, -0.7770],
        [ 0.0275,  0.5881, -0.7770]], grad_fn=<AddmmBackward0>)
loss: 0.882563  [ 1678/ 5464]
tensor([[ 0.0281,  0.5882, -0.7779],
        [ 0.0281,  0.5882, -0.7779]], grad_fn=<AddmmBackward0>)
loss: 1.162401  [ 1680/ 5464]
tensor([[ 0.0290,  0.5880, -0.7789],
        [ 0.0290,  0.5880, -0.7789]], grad_fn=<AddmmBackward0>)
loss: 0.881986  [ 1682/ 5464]
tensor([[ 0.0300,  0.5878, -0.7800],
        [ 0.0300,  0.5878, -0.7800]], grad_fn=<AddmmBackward0>)
loss: 1.286643  [ 1684/ 5464]
tensor([[ 0.0307,  0.5875, -0.7806],
        [ 0.0307,  0.5875, -0.7806]], grad_fn=<AddmmBackward0>)
loss: 1.287068  [ 1686/ 5464]
tensor([[ 0.0311,  0.5873, -0.7808],
        [ 0.0311,  0.5873, -0.7808]], grad_fn=<AddmmBackward0>)
loss: 1.159375  [ 1688/ 5464]
tensor([[ 0.0320,  0.5868, -0.7811],
        [ 0.0320,  0.5868, -0.7811]], grad_fn=<AddmmBackward0>)
loss: 1.565034  [ 1690/ 5464]
tensor([[ 0.0328,  0.5860, -0.7811],
        [ 0.0328

tensor([[ 0.0337,  0.6084, -0.8182],
        [ 0.0337,  0.6084, -0.8182]], grad_fn=<AddmmBackward0>)
loss: 0.876814  [ 1804/ 5464]
tensor([[ 0.0338,  0.6089, -0.8191],
        [ 0.0338,  0.6089, -0.8191]], grad_fn=<AddmmBackward0>)
loss: 0.589127  [ 1806/ 5464]
tensor([[ 0.0337,  0.6096, -0.8201],
        [ 0.0337,  0.6096, -0.8201]], grad_fn=<AddmmBackward0>)
loss: 1.303508  [ 1808/ 5464]
tensor([[ 0.0334,  0.6102, -0.8206],
        [ 0.0334,  0.6102, -0.8206]], grad_fn=<AddmmBackward0>)
loss: 0.876626  [ 1810/ 5464]
tensor([[ 0.0333,  0.6107, -0.8212],
        [ 0.0333,  0.6107, -0.8212]], grad_fn=<AddmmBackward0>)
loss: 0.587907  [ 1812/ 5464]
tensor([[ 0.0330,  0.6114, -0.8219],
        [ 0.0330,  0.6114, -0.8219]], grad_fn=<AddmmBackward0>)
loss: 0.587414  [ 1814/ 5464]
tensor([[ 0.0325,  0.6123, -0.8226],
        [ 0.0325,  0.6123, -0.8226]], grad_fn=<AddmmBackward0>)
loss: 0.876645  [ 1816/ 5464]
tensor([[ 0.0322,  0.6130, -0.8234],
        [ 0.0322,  0.6130, -0.8234]], grad_fn=

tensor([[ 0.0341,  0.6204, -0.8380],
        [ 0.0341,  0.6204, -0.8380]], grad_fn=<AddmmBackward0>)
loss: 0.581691  [ 1930/ 5464]
tensor([[ 0.0335,  0.6210, -0.8380],
        [ 0.0335,  0.6210, -0.8380]], grad_fn=<AddmmBackward0>)
loss: 1.310723  [ 1932/ 5464]
tensor([[ 0.0328,  0.6215, -0.8378],
        [ 0.0328,  0.6215, -0.8378]], grad_fn=<AddmmBackward0>)
loss: 1.604783  [ 1934/ 5464]
tensor([[ 0.0322,  0.6216, -0.8372],
        [ 0.0322,  0.6216, -0.8372]], grad_fn=<AddmmBackward0>)
loss: 0.580622  [ 1936/ 5464]
tensor([[ 0.0315,  0.6220, -0.8369],
        [ 0.0315,  0.6220, -0.8369]], grad_fn=<AddmmBackward0>)
loss: 0.875531  [ 1938/ 5464]
tensor([[ 0.0310,  0.6223, -0.8366],
        [ 0.0310,  0.6223, -0.8366]], grad_fn=<AddmmBackward0>)
loss: 0.875675  [ 1940/ 5464]
tensor([[ 0.0307,  0.6226, -0.8366],
        [ 0.0307,  0.6226, -0.8366]], grad_fn=<AddmmBackward0>)
loss: 0.875765  [ 1942/ 5464]
tensor([[ 0.0305,  0.6228, -0.8366],
        [ 0.0305,  0.6228, -0.8366]], grad_fn=

tensor([[ 0.0230,  0.6407, -0.8547],
        [ 0.0230,  0.6407, -0.8547]], grad_fn=<AddmmBackward0>)
loss: 1.314921  [ 2056/ 5464]
tensor([[ 0.0233,  0.6407, -0.8550],
        [ 0.0233,  0.6407, -0.8550]], grad_fn=<AddmmBackward0>)
loss: 0.875967  [ 2058/ 5464]
tensor([[ 0.0236,  0.6407, -0.8554],
        [ 0.0236,  0.6407, -0.8554]], grad_fn=<AddmmBackward0>)
loss: 0.875847  [ 2060/ 5464]
tensor([[ 0.0240,  0.6406, -0.8559],
        [ 0.0240,  0.6406, -0.8559]], grad_fn=<AddmmBackward0>)
loss: 0.875698  [ 2062/ 5464]
tensor([[ 0.0245,  0.6405, -0.8565],
        [ 0.0245,  0.6405, -0.8565]], grad_fn=<AddmmBackward0>)
loss: 0.567550  [ 2064/ 5464]
tensor([[ 0.0248,  0.6406, -0.8571],
        [ 0.0248,  0.6406, -0.8571]], grad_fn=<AddmmBackward0>)
loss: 1.183322  [ 2066/ 5464]
tensor([[ 0.0254,  0.6404, -0.8578],
        [ 0.0254,  0.6404, -0.8578]], grad_fn=<AddmmBackward0>)
loss: 0.567688  [ 2068/ 5464]
tensor([[ 0.0259,  0.6405, -0.8585],
        [ 0.0259,  0.6405, -0.8585]], grad_fn=

loss: 1.164122  [ 2180/ 5464]
tensor([[ 0.0436,  0.6301, -0.8677],
        [ 0.0436,  0.6301, -0.8677]], grad_fn=<AddmmBackward0>)
loss: 0.869807  [ 2182/ 5464]
tensor([[ 0.0446,  0.6297, -0.8685],
        [ 0.0446,  0.6297, -0.8685]], grad_fn=<AddmmBackward0>)
loss: 0.576929  [ 2184/ 5464]
tensor([[ 0.0453,  0.6296, -0.8693],
        [ 0.0453,  0.6296, -0.8693]], grad_fn=<AddmmBackward0>)
loss: 0.577115  [ 2186/ 5464]
tensor([[ 0.0458,  0.6297, -0.8702],
        [ 0.0458,  0.6297, -0.8702]], grad_fn=<AddmmBackward0>)
loss: 0.577101  [ 2188/ 5464]
tensor([[ 0.0460,  0.6300, -0.8711],
        [ 0.0460,  0.6300, -0.8711]], grad_fn=<AddmmBackward0>)
loss: 0.868932  [ 2190/ 5464]
tensor([[ 0.0463,  0.6303, -0.8720],
        [ 0.0463,  0.6303, -0.8720]], grad_fn=<AddmmBackward0>)
loss: 0.576770  [ 2192/ 5464]
tensor([[ 0.0464,  0.6308, -0.8729],
        [ 0.0464,  0.6308, -0.8729]], grad_fn=<AddmmBackward0>)
loss: 0.868676  [ 2194/ 5464]
tensor([[ 0.0466,  0.6312, -0.8738],
        [ 0.0466

tensor([[ 0.0615,  0.6360, -0.9038],
        [ 0.0615,  0.6360, -0.9038]], grad_fn=<AddmmBackward0>)
loss: 0.862414  [ 2310/ 5464]
tensor([[ 0.0619,  0.6355, -0.9035],
        [ 0.0619,  0.6355, -0.9035]], grad_fn=<AddmmBackward0>)
loss: 1.631847  [ 2312/ 5464]
tensor([[ 0.0624,  0.6347, -0.9030],
        [ 0.0624,  0.6347, -0.9030]], grad_fn=<AddmmBackward0>)
loss: 0.576095  [ 2314/ 5464]
tensor([[ 0.0626,  0.6342, -0.9026],
        [ 0.0626,  0.6342, -0.9026]], grad_fn=<AddmmBackward0>)
loss: 0.576416  [ 2316/ 5464]
tensor([[ 0.0626,  0.6341, -0.9024],
        [ 0.0626,  0.6341, -0.9024]], grad_fn=<AddmmBackward0>)
loss: 0.862259  [ 2318/ 5464]
tensor([[ 0.0627,  0.6339, -0.9022],
        [ 0.0627,  0.6339, -0.9022]], grad_fn=<AddmmBackward0>)
loss: 0.862237  [ 2320/ 5464]
tensor([[ 0.0630,  0.6337, -0.9023],
        [ 0.0630,  0.6337, -0.9023]], grad_fn=<AddmmBackward0>)
loss: 0.862181  [ 2322/ 5464]
tensor([[ 0.0633,  0.6335, -0.9024],
        [ 0.0633,  0.6335, -0.9024]], grad_fn=

tensor([[ 0.0416,  0.6584, -0.9114],
        [ 0.0416,  0.6584, -0.9114]], grad_fn=<AddmmBackward0>)
loss: 2.128121  [ 2436/ 5464]
tensor([[ 0.0407,  0.6587, -0.9104],
        [ 0.0407,  0.6587, -0.9104]], grad_fn=<AddmmBackward0>)
loss: 0.558053  [ 2438/ 5464]
tensor([[ 0.0397,  0.6591, -0.9097],
        [ 0.0397,  0.6591, -0.9097]], grad_fn=<AddmmBackward0>)
loss: 0.557645  [ 2440/ 5464]
tensor([[ 0.0386,  0.6597, -0.9091],
        [ 0.0386,  0.6597, -0.9091]], grad_fn=<AddmmBackward0>)
loss: 0.867681  [ 2442/ 5464]
tensor([[ 0.0377,  0.6603, -0.9087],
        [ 0.0377,  0.6603, -0.9087]], grad_fn=<AddmmBackward0>)
loss: 1.341143  [ 2444/ 5464]
tensor([[ 0.0367,  0.6607, -0.9080],
        [ 0.0367,  0.6607, -0.9080]], grad_fn=<AddmmBackward0>)
loss: 0.868237  [ 2446/ 5464]
tensor([[ 0.0360,  0.6610, -0.9075],
        [ 0.0360,  0.6610, -0.9075]], grad_fn=<AddmmBackward0>)
loss: 0.868471  [ 2448/ 5464]
tensor([[ 0.0354,  0.6613, -0.9071],
        [ 0.0354,  0.6613, -0.9071]], grad_fn=

loss: 0.872938  [ 2560/ 5464]
tensor([[ 0.0128,  0.6985, -0.9348],
        [ 0.0128,  0.6985, -0.9348]], grad_fn=<AddmmBackward0>)
loss: 0.872904  [ 2562/ 5464]
tensor([[ 0.0129,  0.6988, -0.9355],
        [ 0.0129,  0.6988, -0.9355]], grad_fn=<AddmmBackward0>)
loss: 0.529865  [ 2564/ 5464]
tensor([[ 0.0128,  0.6994, -0.9363],
        [ 0.0128,  0.6994, -0.9363]], grad_fn=<AddmmBackward0>)
loss: 0.529529  [ 2566/ 5464]
tensor([[ 0.0125,  0.7001, -0.9370],
        [ 0.0125,  0.7001, -0.9370]], grad_fn=<AddmmBackward0>)
loss: 2.166193  [ 2568/ 5464]
tensor([[ 0.0121,  0.7004, -0.9369],
        [ 0.0121,  0.7004, -0.9369]], grad_fn=<AddmmBackward0>)
loss: 1.691634  [ 2570/ 5464]
tensor([[ 0.0119,  0.7004, -0.9365],
        [ 0.0119,  0.7004, -0.9365]], grad_fn=<AddmmBackward0>)
loss: 0.528817  [ 2572/ 5464]
tensor([[ 0.0115,  0.7006, -0.9362],
        [ 0.0115,  0.7006, -0.9362]], grad_fn=<AddmmBackward0>)
loss: 0.528651  [ 2574/ 5464]
tensor([[ 0.0109,  0.7009, -0.9360],
        [ 0.0109

loss: 1.694362  [ 2690/ 5464]
tensor([[ 0.0179,  0.7006, -0.9459],
        [ 0.0179,  0.7006, -0.9459]], grad_fn=<AddmmBackward0>)
loss: 0.870793  [ 2692/ 5464]
tensor([[ 0.0183,  0.7002, -0.9458],
        [ 0.0183,  0.7002, -0.9458]], grad_fn=<AddmmBackward0>)
loss: 0.529715  [ 2694/ 5464]
tensor([[ 0.0185,  0.7001, -0.9459],
        [ 0.0185,  0.7001, -0.9459]], grad_fn=<AddmmBackward0>)
loss: 0.529808  [ 2696/ 5464]
tensor([[ 0.0185,  0.7002, -0.9461],
        [ 0.0185,  0.7002, -0.9461]], grad_fn=<AddmmBackward0>)
loss: 0.870617  [ 2698/ 5464]
tensor([[ 0.0186,  0.7003, -0.9464],
        [ 0.0186,  0.7003, -0.9464]], grad_fn=<AddmmBackward0>)
loss: 0.870571  [ 2700/ 5464]
tensor([[ 0.0188,  0.7003, -0.9467],
        [ 0.0188,  0.7003, -0.9467]], grad_fn=<AddmmBackward0>)
loss: 0.529733  [ 2702/ 5464]
tensor([[ 0.0188,  0.7005, -0.9471],
        [ 0.0188,  0.7005, -0.9471]], grad_fn=<AddmmBackward0>)
loss: 0.529595  [ 2704/ 5464]
tensor([[ 0.0186,  0.7010, -0.9476],
        [ 0.0186

loss: 0.878879  [ 2816/ 5464]
tensor([[-0.0089,  0.7220, -0.9417],
        [-0.0089,  0.7220, -0.9417]], grad_fn=<AddmmBackward0>)
loss: 0.513355  [ 2818/ 5464]
tensor([[-0.0089,  0.7217, -0.9413],
        [-0.0089,  0.7217, -0.9413]], grad_fn=<AddmmBackward0>)
loss: 0.513539  [ 2820/ 5464]
tensor([[-0.0090,  0.7217, -0.9410],
        [-0.0090,  0.7217, -0.9410]], grad_fn=<AddmmBackward0>)
loss: 1.244215  [ 2822/ 5464]
tensor([[-0.0087,  0.7213, -0.9409],
        [-0.0087,  0.7213, -0.9409]], grad_fn=<AddmmBackward0>)
loss: 1.344909  [ 2824/ 5464]
tensor([[-0.0085,  0.7209, -0.9404],
        [-0.0085,  0.7209, -0.9404]], grad_fn=<AddmmBackward0>)
loss: 0.878780  [ 2826/ 5464]
tensor([[-0.0083,  0.7205, -0.9401],
        [-0.0083,  0.7205, -0.9401]], grad_fn=<AddmmBackward0>)
loss: 0.878726  [ 2828/ 5464]
tensor([[-0.0080,  0.7201, -0.9399],
        [-0.0080,  0.7201, -0.9399]], grad_fn=<AddmmBackward0>)
loss: 0.878633  [ 2830/ 5464]
tensor([[-0.0075,  0.7196, -0.9399],
        [-0.0075

tensor([[-0.0137,  0.7246, -0.9390],
        [-0.0137,  0.7246, -0.9390]], grad_fn=<AddmmBackward0>)
loss: 0.880404  [ 2944/ 5464]
tensor([[-0.0133,  0.7243, -0.9390],
        [-0.0133,  0.7243, -0.9390]], grad_fn=<AddmmBackward0>)
loss: 1.343139  [ 2946/ 5464]
tensor([[-0.0131,  0.7239, -0.9387],
        [-0.0131,  0.7239, -0.9387]], grad_fn=<AddmmBackward0>)
loss: 0.880250  [ 2948/ 5464]
tensor([[-0.0129,  0.7235, -0.9385],
        [-0.0129,  0.7235, -0.9385]], grad_fn=<AddmmBackward0>)
loss: 1.343006  [ 2950/ 5464]
tensor([[-0.0128,  0.7232, -0.9380],
        [-0.0128,  0.7232, -0.9380]], grad_fn=<AddmmBackward0>)
loss: 0.512212  [ 2952/ 5464]
tensor([[-0.0129,  0.7230, -0.9377],
        [-0.0129,  0.7230, -0.9377]], grad_fn=<AddmmBackward0>)
loss: 0.880227  [ 2954/ 5464]
tensor([[-0.0128,  0.7229, -0.9374],
        [-0.0128,  0.7229, -0.9374]], grad_fn=<AddmmBackward0>)
loss: 0.512374  [ 2956/ 5464]
tensor([[-0.0130,  0.7229, -0.9373],
        [-0.0130,  0.7229, -0.9373]], grad_fn=

loss: 0.504085  [ 3068/ 5464]
tensor([[-0.0112,  0.7375, -0.9632],
        [-0.0112,  0.7375, -0.9632]], grad_fn=<AddmmBackward0>)
loss: 1.252793  [ 3070/ 5464]
tensor([[-0.0108,  0.7370, -0.9631],
        [-0.0108,  0.7370, -0.9631]], grad_fn=<AddmmBackward0>)
loss: 0.878341  [ 3072/ 5464]
tensor([[-0.0103,  0.7366, -0.9632],
        [-0.0103,  0.7366, -0.9632]], grad_fn=<AddmmBackward0>)
loss: 0.504760  [ 3074/ 5464]
tensor([[-0.0100,  0.7364, -0.9633],
        [-0.0100,  0.7364, -0.9633]], grad_fn=<AddmmBackward0>)
loss: 0.504898  [ 3076/ 5464]
tensor([[-0.0099,  0.7365, -0.9635],
        [-0.0099,  0.7365, -0.9635]], grad_fn=<AddmmBackward0>)
loss: 0.878059  [ 3078/ 5464]
tensor([[-0.0097,  0.7365, -0.9638],
        [-0.0097,  0.7365, -0.9638]], grad_fn=<AddmmBackward0>)
loss: 1.355020  [ 3080/ 5464]
tensor([[-0.0097,  0.7364, -0.9637],
        [-0.0097,  0.7364, -0.9637]], grad_fn=<AddmmBackward0>)
loss: 1.251044  [ 3082/ 5464]
tensor([[-0.0092,  0.7360, -0.9637],
        [-0.0092

loss: 2.193198  [ 3196/ 5464]
tensor([[ 0.0067,  0.7170, -0.9563],
        [ 0.0067,  0.7170, -0.9563]], grad_fn=<AddmmBackward0>)
loss: 0.518262  [ 3198/ 5464]
tensor([[ 0.0063,  0.7167, -0.9552],
        [ 0.0063,  0.7167, -0.9552]], grad_fn=<AddmmBackward0>)
loss: 0.873608  [ 3200/ 5464]
tensor([[ 0.0060,  0.7164, -0.9543],
        [ 0.0060,  0.7164, -0.9543]], grad_fn=<AddmmBackward0>)
loss: 0.873730  [ 3202/ 5464]
tensor([[ 0.0059,  0.7160, -0.9536],
        [ 0.0059,  0.7160, -0.9536]], grad_fn=<AddmmBackward0>)
loss: 0.873797  [ 3204/ 5464]
tensor([[ 0.0059,  0.7157, -0.9531],
        [ 0.0059,  0.7157, -0.9531]], grad_fn=<AddmmBackward0>)
loss: 0.873814  [ 3206/ 5464]
tensor([[ 0.0061,  0.7153, -0.9527],
        [ 0.0061,  0.7153, -0.9527]], grad_fn=<AddmmBackward0>)
loss: 0.519191  [ 3208/ 5464]
tensor([[ 0.0060,  0.7152, -0.9525],
        [ 0.0060,  0.7152, -0.9525]], grad_fn=<AddmmBackward0>)
loss: 0.873810  [ 3210/ 5464]
tensor([[ 0.0061,  0.7150, -0.9524],
        [ 0.0061

loss: 1.708966  [ 3326/ 5464]
tensor([[ 0.0134,  0.7133, -0.9600],
        [ 0.0134,  0.7133, -0.9600]], grad_fn=<AddmmBackward0>)
loss: 0.521336  [ 3328/ 5464]
tensor([[ 0.0145,  0.7123, -0.9601],
        [ 0.0145,  0.7123, -0.9601]], grad_fn=<AddmmBackward0>)
loss: 1.219890  [ 3330/ 5464]
tensor([[ 0.0159,  0.7112, -0.9603],
        [ 0.0159,  0.7112, -0.9603]], grad_fn=<AddmmBackward0>)
loss: 0.522899  [ 3332/ 5464]
tensor([[ 0.0170,  0.7103, -0.9606],
        [ 0.0170,  0.7103, -0.9606]], grad_fn=<AddmmBackward0>)
loss: 1.358973  [ 3334/ 5464]
tensor([[ 0.0178,  0.7095, -0.9604],
        [ 0.0178,  0.7095, -0.9604]], grad_fn=<AddmmBackward0>)
loss: 1.215870  [ 3336/ 5464]
tensor([[ 0.0189,  0.7085, -0.9604],
        [ 0.0189,  0.7085, -0.9604]], grad_fn=<AddmmBackward0>)
loss: 0.524869  [ 3338/ 5464]
tensor([[ 0.0198,  0.7078, -0.9606],
        [ 0.0198,  0.7078, -0.9606]], grad_fn=<AddmmBackward0>)
loss: 1.359573  [ 3340/ 5464]
tensor([[ 0.0204,  0.7071, -0.9603],
        [ 0.0204

loss: 0.863784  [ 3452/ 5464]
tensor([[ 0.0362,  0.7065, -0.9823],
        [ 0.0362,  0.7065, -0.9823]], grad_fn=<AddmmBackward0>)
loss: 0.863593  [ 3454/ 5464]
tensor([[ 0.0370,  0.7058, -0.9823],
        [ 0.0370,  0.7058, -0.9823]], grad_fn=<AddmmBackward0>)
loss: 0.863381  [ 3456/ 5464]
tensor([[ 0.0378,  0.7052, -0.9825],
        [ 0.0378,  0.7052, -0.9825]], grad_fn=<AddmmBackward0>)
loss: 0.863152  [ 3458/ 5464]
tensor([[ 0.0386,  0.7046, -0.9827],
        [ 0.0386,  0.7046, -0.9827]], grad_fn=<AddmmBackward0>)
loss: 0.529920  [ 3460/ 5464]
tensor([[ 0.0392,  0.7042, -0.9830],
        [ 0.0392,  0.7042, -0.9830]], grad_fn=<AddmmBackward0>)
loss: 0.530193  [ 3462/ 5464]
tensor([[ 0.0395,  0.7042, -0.9834],
        [ 0.0395,  0.7042, -0.9834]], grad_fn=<AddmmBackward0>)
loss: 1.374058  [ 3464/ 5464]
tensor([[ 0.0396,  0.7041, -0.9834],
        [ 0.0396,  0.7041, -0.9834]], grad_fn=<AddmmBackward0>)
loss: 0.862594  [ 3466/ 5464]
tensor([[ 0.0398,  0.7039, -0.9834],
        [ 0.0398

tensor([[ 0.0583,  0.6990, -1.0027],
        [ 0.0583,  0.6990, -1.0027]], grad_fn=<AddmmBackward0>)
loss: 0.536079  [ 3582/ 5464]
tensor([[ 0.0577,  0.6997, -1.0029],
        [ 0.0577,  0.6997, -1.0029]], grad_fn=<AddmmBackward0>)
loss: 0.856582  [ 3584/ 5464]
tensor([[ 0.0573,  0.7003, -1.0032],
        [ 0.0573,  0.7003, -1.0032]], grad_fn=<AddmmBackward0>)
loss: 0.535186  [ 3586/ 5464]
tensor([[ 0.0567,  0.7010, -1.0035],
        [ 0.0567,  0.7010, -1.0035]], grad_fn=<AddmmBackward0>)
loss: 0.534661  [ 3588/ 5464]
tensor([[ 0.0560,  0.7019, -1.0039],
        [ 0.0560,  0.7019, -1.0039]], grad_fn=<AddmmBackward0>)
loss: 0.534022  [ 3590/ 5464]
tensor([[ 0.0552,  0.7030, -1.0044],
        [ 0.0552,  0.7030, -1.0044]], grad_fn=<AddmmBackward0>)
loss: 1.710894  [ 3592/ 5464]
tensor([[ 0.0545,  0.7036, -1.0045],
        [ 0.0545,  0.7036, -1.0045]], grad_fn=<AddmmBackward0>)
loss: 1.386860  [ 3594/ 5464]
tensor([[ 0.0538,  0.7041, -1.0042],
        [ 0.0538,  0.7041, -1.0042]], grad_fn=

loss: 0.525321  [ 3706/ 5464]
tensor([[ 0.0572,  0.7174, -1.0308],
        [ 0.0572,  0.7174, -1.0308]], grad_fn=<AddmmBackward0>)
loss: 0.855313  [ 3708/ 5464]
tensor([[ 0.0576,  0.7176, -1.0315],
        [ 0.0576,  0.7176, -1.0315]], grad_fn=<AddmmBackward0>)
loss: 0.855193  [ 3710/ 5464]
tensor([[ 0.0580,  0.7176, -1.0322],
        [ 0.0580,  0.7176, -1.0322]], grad_fn=<AddmmBackward0>)
loss: 0.525213  [ 3712/ 5464]
tensor([[ 0.0581,  0.7179, -1.0330],
        [ 0.0581,  0.7179, -1.0330]], grad_fn=<AddmmBackward0>)
loss: 0.525066  [ 3714/ 5464]
tensor([[ 0.0581,  0.7184, -1.0338],
        [ 0.0581,  0.7184, -1.0338]], grad_fn=<AddmmBackward0>)
loss: 1.731035  [ 3716/ 5464]
tensor([[ 0.0582,  0.7186, -1.0341],
        [ 0.0582,  0.7186, -1.0341]], grad_fn=<AddmmBackward0>)
loss: 0.524717  [ 3718/ 5464]
tensor([[ 0.0581,  0.7189, -1.0345],
        [ 0.0581,  0.7189, -1.0345]], grad_fn=<AddmmBackward0>)
loss: 1.401184  [ 3720/ 5464]
tensor([[ 0.0578,  0.7191, -1.0344],
        [ 0.0578

loss: 0.858736  [ 3834/ 5464]
tensor([[ 0.0473,  0.7191, -1.0189],
        [ 0.0473,  0.7191, -1.0189]], grad_fn=<AddmmBackward0>)
loss: 0.858647  [ 3836/ 5464]
tensor([[ 0.0477,  0.7188, -1.0191],
        [ 0.0477,  0.7188, -1.0191]], grad_fn=<AddmmBackward0>)
loss: 1.391922  [ 3838/ 5464]
tensor([[ 0.0479,  0.7185, -1.0189],
        [ 0.0479,  0.7185, -1.0189]], grad_fn=<AddmmBackward0>)
loss: 0.523156  [ 3840/ 5464]
tensor([[ 0.0478,  0.7185, -1.0187],
        [ 0.0478,  0.7185, -1.0187]], grad_fn=<AddmmBackward0>)
loss: 0.523173  [ 3842/ 5464]
tensor([[ 0.0476,  0.7187, -1.0187],
        [ 0.0476,  0.7187, -1.0187]], grad_fn=<AddmmBackward0>)
loss: 0.523027  [ 3844/ 5464]
tensor([[ 0.0472,  0.7191, -1.0188],
        [ 0.0472,  0.7191, -1.0188]], grad_fn=<AddmmBackward0>)
loss: 0.522733  [ 3846/ 5464]
tensor([[ 0.0467,  0.7197, -1.0190],
        [ 0.0467,  0.7197, -1.0190]], grad_fn=<AddmmBackward0>)
loss: 0.522308  [ 3848/ 5464]
tensor([[ 0.0460,  0.7205, -1.0192],
        [ 0.0460

tensor([[ 0.0201,  0.7571, -1.0402],
        [ 0.0201,  0.7571, -1.0402]], grad_fn=<AddmmBackward0>)
loss: 0.497324  [ 3964/ 5464]
tensor([[ 0.0201,  0.7573, -1.0406],
        [ 0.0201,  0.7573, -1.0406]], grad_fn=<AddmmBackward0>)
loss: 0.865802  [ 3966/ 5464]
tensor([[ 0.0202,  0.7575, -1.0411],
        [ 0.0202,  0.7575, -1.0411]], grad_fn=<AddmmBackward0>)
loss: 0.865749  [ 3968/ 5464]
tensor([[ 0.0204,  0.7576, -1.0416],
        [ 0.0204,  0.7576, -1.0416]], grad_fn=<AddmmBackward0>)
loss: 0.865658  [ 3970/ 5464]
tensor([[ 0.0208,  0.7577, -1.0422],
        [ 0.0208,  0.7577, -1.0422]], grad_fn=<AddmmBackward0>)
loss: 0.865533  [ 3972/ 5464]
tensor([[ 0.0212,  0.7576, -1.0428],
        [ 0.0212,  0.7576, -1.0428]], grad_fn=<AddmmBackward0>)
loss: 1.397374  [ 3974/ 5464]
tensor([[ 0.0214,  0.7575, -1.0430],
        [ 0.0214,  0.7575, -1.0430]], grad_fn=<AddmmBackward0>)
loss: 1.397495  [ 3976/ 5464]
tensor([[ 0.0214,  0.7574, -1.0427],
        [ 0.0214,  0.7574, -1.0427]], grad_fn=

loss: 0.500566  [ 4088/ 5464]
tensor([[ 0.0238,  0.7531, -1.0394],
        [ 0.0238,  0.7531, -1.0394]], grad_fn=<AddmmBackward0>)
loss: 0.864688  [ 4090/ 5464]
tensor([[ 0.0232,  0.7536, -1.0393],
        [ 0.0232,  0.7536, -1.0393]], grad_fn=<AddmmBackward0>)
loss: 0.864892  [ 4092/ 5464]
tensor([[ 0.0227,  0.7540, -1.0393],
        [ 0.0227,  0.7540, -1.0393]], grad_fn=<AddmmBackward0>)
loss: 0.499375  [ 4094/ 5464]
tensor([[ 0.0221,  0.7546, -1.0393],
        [ 0.0221,  0.7546, -1.0393]], grad_fn=<AddmmBackward0>)
loss: 0.498952  [ 4096/ 5464]
tensor([[ 0.0214,  0.7554, -1.0395],
        [ 0.0214,  0.7554, -1.0395]], grad_fn=<AddmmBackward0>)
loss: 0.865427  [ 4098/ 5464]
tensor([[ 0.0209,  0.7560, -1.0398],
        [ 0.0209,  0.7560, -1.0398]], grad_fn=<AddmmBackward0>)
loss: 0.865578  [ 4100/ 5464]
tensor([[ 0.0205,  0.7565, -1.0401],
        [ 0.0205,  0.7565, -1.0401]], grad_fn=<AddmmBackward0>)
loss: 1.395991  [ 4102/ 5464]
tensor([[ 0.0200,  0.7569, -1.0400],
        [ 0.0200

tensor([[ 0.0376,  0.7469, -1.0500],
        [ 0.0376,  0.7469, -1.0500]], grad_fn=<AddmmBackward0>)
loss: 0.505506  [ 4216/ 5464]
tensor([[ 0.0381,  0.7465, -1.0501],
        [ 0.0381,  0.7465, -1.0501]], grad_fn=<AddmmBackward0>)
loss: 0.859998  [ 4218/ 5464]
tensor([[ 0.0386,  0.7462, -1.0503],
        [ 0.0386,  0.7462, -1.0503]], grad_fn=<AddmmBackward0>)
loss: 1.213635  [ 4220/ 5464]
tensor([[ 0.0395,  0.7455, -1.0505],
        [ 0.0395,  0.7455, -1.0505]], grad_fn=<AddmmBackward0>)
loss: 0.506556  [ 4222/ 5464]
tensor([[ 0.0401,  0.7451, -1.0509],
        [ 0.0401,  0.7451, -1.0509]], grad_fn=<AddmmBackward0>)
loss: 0.506861  [ 4224/ 5464]
tensor([[ 0.0405,  0.7450, -1.0512],
        [ 0.0405,  0.7450, -1.0512]], grad_fn=<AddmmBackward0>)
loss: 0.859241  [ 4226/ 5464]
tensor([[ 0.0409,  0.7448, -1.0517],
        [ 0.0409,  0.7448, -1.0517]], grad_fn=<AddmmBackward0>)
loss: 0.859087  [ 4228/ 5464]
tensor([[ 0.0415,  0.7446, -1.0522],
        [ 0.0415,  0.7446, -1.0522]], grad_fn=

tensor([[ 0.0775,  0.7164, -1.0608],
        [ 0.0775,  0.7164, -1.0608]], grad_fn=<AddmmBackward0>)
loss: 0.528865  [ 4342/ 5464]
tensor([[ 0.0782,  0.7158, -1.0610],
        [ 0.0782,  0.7158, -1.0610]], grad_fn=<AddmmBackward0>)
loss: 1.417683  [ 4344/ 5464]
tensor([[ 0.0786,  0.7153, -1.0608],
        [ 0.0786,  0.7153, -1.0608]], grad_fn=<AddmmBackward0>)
loss: 1.736042  [ 4346/ 5464]
tensor([[ 0.0791,  0.7145, -1.0602],
        [ 0.0791,  0.7145, -1.0602]], grad_fn=<AddmmBackward0>)
loss: 0.530192  [ 4348/ 5464]
tensor([[ 0.0794,  0.7140, -1.0598],
        [ 0.0794,  0.7140, -1.0598]], grad_fn=<AddmmBackward0>)
loss: 1.417419  [ 4350/ 5464]
tensor([[ 0.0794,  0.7135, -1.0591],
        [ 0.0794,  0.7135, -1.0591]], grad_fn=<AddmmBackward0>)
loss: 0.847862  [ 4352/ 5464]
tensor([[ 0.0796,  0.7130, -1.0585],
        [ 0.0796,  0.7130, -1.0585]], grad_fn=<AddmmBackward0>)
loss: 0.531117  [ 4354/ 5464]
tensor([[ 0.0795,  0.7128, -1.0581],
        [ 0.0795,  0.7128, -1.0581]], grad_fn=

tensor([[ 0.0876,  0.7161, -1.0760],
        [ 0.0876,  0.7161, -1.0760]], grad_fn=<AddmmBackward0>)
loss: 1.159146  [ 4468/ 5464]
tensor([[ 0.0884,  0.7159, -1.0769],
        [ 0.0884,  0.7159, -1.0769]], grad_fn=<AddmmBackward0>)
loss: 0.844636  [ 4470/ 5464]
tensor([[ 0.0892,  0.7157, -1.0777],
        [ 0.0892,  0.7157, -1.0777]], grad_fn=<AddmmBackward0>)
loss: 1.741105  [ 4472/ 5464]
tensor([[ 0.0900,  0.7152, -1.0781],
        [ 0.0900,  0.7152, -1.0781]], grad_fn=<AddmmBackward0>)
loss: 0.531563  [ 4474/ 5464]
tensor([[ 0.0906,  0.7149, -1.0786],
        [ 0.0906,  0.7149, -1.0786]], grad_fn=<AddmmBackward0>)
loss: 1.428528  [ 4476/ 5464]
tensor([[ 0.0909,  0.7146, -1.0786],
        [ 0.0909,  0.7146, -1.0786]], grad_fn=<AddmmBackward0>)
loss: 0.843893  [ 4478/ 5464]
tensor([[ 0.0913,  0.7143, -1.0787],
        [ 0.0913,  0.7143, -1.0787]], grad_fn=<AddmmBackward0>)
loss: 2.325232  [ 4480/ 5464]
tensor([[ 0.0914,  0.7137, -1.0779],
        [ 0.0914,  0.7137, -1.0779]], grad_fn=

tensor([[ 0.0965,  0.7197, -1.0957],
        [ 0.0965,  0.7197, -1.0957]], grad_fn=<AddmmBackward0>)
loss: 0.530034  [ 4594/ 5464]
tensor([[ 0.0965,  0.7200, -1.0961],
        [ 0.0965,  0.7200, -1.0961]], grad_fn=<AddmmBackward0>)
loss: 0.841634  [ 4596/ 5464]
tensor([[ 0.0966,  0.7202, -1.0966],
        [ 0.0966,  0.7202, -1.0966]], grad_fn=<AddmmBackward0>)
loss: 0.841589  [ 4598/ 5464]
tensor([[ 0.0968,  0.7203, -1.0971],
        [ 0.0968,  0.7203, -1.0971]], grad_fn=<AddmmBackward0>)
loss: 0.841514  [ 4600/ 5464]
tensor([[ 0.0970,  0.7204, -1.0977],
        [ 0.0970,  0.7204, -1.0977]], grad_fn=<AddmmBackward0>)
loss: 0.841413  [ 4602/ 5464]
tensor([[ 0.0974,  0.7204, -1.0983],
        [ 0.0974,  0.7204, -1.0983]], grad_fn=<AddmmBackward0>)
loss: 0.529786  [ 4604/ 5464]
tensor([[ 0.0976,  0.7207, -1.0989],
        [ 0.0976,  0.7207, -1.0989]], grad_fn=<AddmmBackward0>)
loss: 1.439458  [ 4606/ 5464]
tensor([[ 0.0975,  0.7208, -1.0991],
        [ 0.0975,  0.7208, -1.0991]], grad_fn=

tensor([[ 0.0871,  0.7350, -1.1063],
        [ 0.0871,  0.7350, -1.1063]], grad_fn=<AddmmBackward0>)
loss: 0.519843  [ 4720/ 5464]
tensor([[ 0.0872,  0.7350, -1.1066],
        [ 0.0872,  0.7350, -1.1066]], grad_fn=<AddmmBackward0>)
loss: 0.843740  [ 4722/ 5464]
tensor([[ 0.0875,  0.7350, -1.1070],
        [ 0.0875,  0.7350, -1.1070]], grad_fn=<AddmmBackward0>)
loss: 0.519886  [ 4724/ 5464]
tensor([[ 0.0875,  0.7352, -1.1074],
        [ 0.0875,  0.7352, -1.1074]], grad_fn=<AddmmBackward0>)
loss: 0.843630  [ 4726/ 5464]
tensor([[ 0.0876,  0.7354, -1.1079],
        [ 0.0876,  0.7354, -1.1079]], grad_fn=<AddmmBackward0>)
loss: 1.441336  [ 4728/ 5464]
tensor([[ 0.0876,  0.7355, -1.1079],
        [ 0.0876,  0.7355, -1.1079]], grad_fn=<AddmmBackward0>)
loss: 1.441342  [ 4730/ 5464]
tensor([[ 0.0873,  0.7355, -1.1076],
        [ 0.0873,  0.7355, -1.1076]], grad_fn=<AddmmBackward0>)
loss: 0.519598  [ 4732/ 5464]
tensor([[ 0.0869,  0.7357, -1.1074],
        [ 0.0869,  0.7357, -1.1074]], grad_fn=

loss: 0.848587  [ 4844/ 5464]
tensor([[ 0.0709,  0.7451, -1.0983],
        [ 0.0709,  0.7451, -1.0983]], grad_fn=<AddmmBackward0>)
loss: 0.848624  [ 4846/ 5464]
tensor([[ 0.0709,  0.7455, -1.0989],
        [ 0.0709,  0.7455, -1.0989]], grad_fn=<AddmmBackward0>)
loss: 1.185922  [ 4848/ 5464]
tensor([[ 0.0713,  0.7455, -1.0995],
        [ 0.0713,  0.7455, -1.0995]], grad_fn=<AddmmBackward0>)
loss: 0.511359  [ 4850/ 5464]
tensor([[ 0.0714,  0.7458, -1.1002],
        [ 0.0714,  0.7458, -1.1002]], grad_fn=<AddmmBackward0>)
loss: 1.185599  [ 4852/ 5464]
tensor([[ 0.0720,  0.7457, -1.1009],
        [ 0.0720,  0.7457, -1.1009]], grad_fn=<AddmmBackward0>)
loss: 0.511395  [ 4854/ 5464]
tensor([[ 0.0723,  0.7458, -1.1016],
        [ 0.0723,  0.7458, -1.1016]], grad_fn=<AddmmBackward0>)
loss: 0.511376  [ 4856/ 5464]
tensor([[ 0.0724,  0.7462, -1.1023],
        [ 0.0724,  0.7462, -1.1023]], grad_fn=<AddmmBackward0>)
loss: 0.511198  [ 4858/ 5464]
tensor([[ 0.0723,  0.7467, -1.1030],
        [ 0.0723

loss: 0.514745  [ 4974/ 5464]
tensor([[ 0.0817,  0.7425, -1.1105],
        [ 0.0817,  0.7425, -1.1105]], grad_fn=<AddmmBackward0>)
loss: 0.514759  [ 4976/ 5464]
tensor([[ 0.0813,  0.7426, -1.1100],
        [ 0.0813,  0.7426, -1.1100]], grad_fn=<AddmmBackward0>)
loss: 1.771581  [ 4978/ 5464]
tensor([[ 0.0809,  0.7424, -1.1091],
        [ 0.0809,  0.7424, -1.1091]], grad_fn=<AddmmBackward0>)
loss: 0.514688  [ 4980/ 5464]
tensor([[ 0.0805,  0.7424, -1.1084],
        [ 0.0805,  0.7424, -1.1084]], grad_fn=<AddmmBackward0>)
loss: 1.440009  [ 4982/ 5464]
tensor([[ 0.0798,  0.7424, -1.1074],
        [ 0.0798,  0.7424, -1.1074]], grad_fn=<AddmmBackward0>)
loss: 0.514516  [ 4984/ 5464]
tensor([[ 0.0791,  0.7426, -1.1066],
        [ 0.0791,  0.7426, -1.1066]], grad_fn=<AddmmBackward0>)
loss: 0.846012  [ 4986/ 5464]
tensor([[ 0.0785,  0.7427, -1.1060],
        [ 0.0785,  0.7427, -1.1060]], grad_fn=<AddmmBackward0>)
loss: 0.514121  [ 4988/ 5464]
tensor([[ 0.0778,  0.7430, -1.1055],
        [ 0.0778

loss: 0.504491  [ 5102/ 5464]
tensor([[ 0.0636,  0.7561, -1.1053],
        [ 0.0636,  0.7561, -1.1053]], grad_fn=<AddmmBackward0>)
loss: 0.504275  [ 5104/ 5464]
tensor([[ 0.0630,  0.7565, -1.1053],
        [ 0.0630,  0.7565, -1.1053]], grad_fn=<AddmmBackward0>)
loss: 0.850682  [ 5106/ 5464]
tensor([[ 0.0627,  0.7569, -1.1054],
        [ 0.0627,  0.7569, -1.1054]], grad_fn=<AddmmBackward0>)
loss: 0.503662  [ 5108/ 5464]
tensor([[ 0.0622,  0.7575, -1.1056],
        [ 0.0622,  0.7575, -1.1056]], grad_fn=<AddmmBackward0>)
loss: 0.503271  [ 5110/ 5464]
tensor([[ 0.0615,  0.7582, -1.1058],
        [ 0.0615,  0.7582, -1.1058]], grad_fn=<AddmmBackward0>)
loss: 1.434777  [ 5112/ 5464]
tensor([[ 0.0608,  0.7588, -1.1056],
        [ 0.0608,  0.7588, -1.1056]], grad_fn=<AddmmBackward0>)
loss: 1.783567  [ 5114/ 5464]
tensor([[ 0.0602,  0.7590, -1.1051],
        [ 0.0602,  0.7590, -1.1051]], grad_fn=<AddmmBackward0>)
loss: 0.851517  [ 5116/ 5464]
tensor([[ 0.0598,  0.7591, -1.1047],
        [ 0.0598

loss: 0.516448  [ 5232/ 5464]
tensor([[ 0.0745,  0.7371, -1.0906],
        [ 0.0745,  0.7371, -1.0906]], grad_fn=<AddmmBackward0>)
loss: 0.516613  [ 5234/ 5464]
tensor([[ 0.0746,  0.7371, -1.0908],
        [ 0.0746,  0.7371, -1.0908]], grad_fn=<AddmmBackward0>)
loss: 0.847842  [ 5236/ 5464]
tensor([[ 0.0748,  0.7371, -1.0911],
        [ 0.0748,  0.7371, -1.0911]], grad_fn=<AddmmBackward0>)
loss: 0.516639  [ 5238/ 5464]
tensor([[ 0.0748,  0.7373, -1.0914],
        [ 0.0748,  0.7373, -1.0914]], grad_fn=<AddmmBackward0>)
loss: 0.847761  [ 5240/ 5464]
tensor([[ 0.0750,  0.7375, -1.0919],
        [ 0.0750,  0.7375, -1.0919]], grad_fn=<AddmmBackward0>)
loss: 0.516451  [ 5242/ 5464]
tensor([[ 0.0749,  0.7378, -1.0923],
        [ 0.0749,  0.7378, -1.0923]], grad_fn=<AddmmBackward0>)
loss: 0.516233  [ 5244/ 5464]
tensor([[ 0.0746,  0.7384, -1.0928],
        [ 0.0746,  0.7384, -1.0928]], grad_fn=<AddmmBackward0>)
loss: 0.515877  [ 5246/ 5464]
tensor([[ 0.0742,  0.7391, -1.0934],
        [ 0.0742

loss: 0.508594  [ 5358/ 5464]
tensor([[ 0.0638,  0.7494, -1.0947],
        [ 0.0638,  0.7494, -1.0947]], grad_fn=<AddmmBackward0>)
loss: 0.508011  [ 5360/ 5464]
tensor([[ 0.0629,  0.7503, -1.0950],
        [ 0.0629,  0.7503, -1.0950]], grad_fn=<AddmmBackward0>)
loss: 0.851032  [ 5362/ 5464]
tensor([[ 0.0623,  0.7512, -1.0954],
        [ 0.0623,  0.7512, -1.0954]], grad_fn=<AddmmBackward0>)
loss: 0.851209  [ 5364/ 5464]
tensor([[ 0.0618,  0.7519, -1.0958],
        [ 0.0618,  0.7519, -1.0958]], grad_fn=<AddmmBackward0>)
loss: 0.851330  [ 5366/ 5464]
tensor([[ 0.0615,  0.7524, -1.0963],
        [ 0.0615,  0.7524, -1.0963]], grad_fn=<AddmmBackward0>)
loss: 0.505962  [ 5368/ 5464]
tensor([[ 0.0611,  0.7531, -1.0968],
        [ 0.0611,  0.7531, -1.0968]], grad_fn=<AddmmBackward0>)
loss: 0.851516  [ 5370/ 5464]
tensor([[ 0.0608,  0.7537, -1.0974],
        [ 0.0608,  0.7537, -1.0974]], grad_fn=<AddmmBackward0>)
loss: 1.430654  [ 5372/ 5464]
tensor([[ 0.0603,  0.7542, -1.0975],
        [ 0.0603

In [511]:
!pip install torchviz

  Created wheel for torchviz: filename=torchviz-0.0.2-py3-none-any.whl size=4151 sha256=25e4815f5ffe73094584ce52b095e8022264684c519dcdfa0eadf8ac71ed1c72
  Stored in directory: c:\users\moon computer\appdata\local\pip\cache\wheels\05\7d\1b\8306781244e42ede119edbb053bdcda1c1f424ca226165a417
Successfully built torchviz


In [ ]:
Y=model(X)

In [ ]:
from torchviz import make_dot
make_dot(Y.mean(), params=dict(model.named_parameters())).render("attached", format="png")